### ISSUE TITLE
Explorer icons not loading

### ISSUE THREAD

**Issue by 1mmxw** [AntiBoomz/BTRoblox#124]
![Image](https://github.com/user-attachments/assets/e802408f-bf68-4ba2-b4ec-e535001ddcc1)

yea im creating this issue again, i found the error:
```js
	const explorerIconPromise = new Promise(resolve => {
		// Asset id: 12706538541
		AssetCache.loadBuffer("https://c5.rbxcdn.com/c17885601281c2beda436c55fcedb9cc", { cache: false }).then(buffer => {
			const reader = new FileReader()
			reader.onload = () => resolve(reader.result)
			reader.readAsDataURL(new Blob([new Uint8Array(buffer)], { type: "image/png" }))
		})
	})
```
i think `c5.rbxcdn.com` dont work anymore so u can replace the url with this https://assetdelivery.roblox.com/v1/asset/?id=12706538541

i had to fix it with my css editor using this
```css
.btr-explorer-parent {
  --btr-explorer-icons: url(https://assetdelivery.roblox.com/v1/asset/?id=12706538541);
}
```

applying changes:

![Image](https://github.com/user-attachments/assets/1b60fb3a-256c-435d-a99f-0ffea16a1ffa)
